name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        env:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login --username $username --password-stdin
      - name: Build Docker image
        run: docker build Distal.Core --file Distal.Core/Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/distal.core:${{ github.ref_name }}
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/distal.core:${{ github.ref_name }}
